export class LotfpSpell {
    name: string;
    level: number;
    description: string;
}


export const clericSpells: LotfpSpell[] = [
    { name: 'Bless', level: 1, description: '' },
    { name: 'Command', level: 1, description: '' },
    { name: 'Cure light wounds', level: 1, description: '' },
    { name: 'Detect evil', level: 1, description: '' },
    { name: 'Invisibility to undead', level: 1, description: '' },
    { name: 'Protection from evil', level: 1, description: '' },
    { name: 'Purify food & drink', level: 1, description: '' },
    { name: 'Remove fear', level: 1, description: '' },
    { name: 'Sanctuary', level: 1, description: '' },
    { name: 'Turn undead', level: 1, description: '' },

    { name: 'Augury', level: 2, description: '' },
    { name: 'Delay poison', level: 2, description: '' },
    { name: 'Enthrall', level: 2, description: '' },
    { name: 'Heat metal', level: 2, description: '' },
    { name: 'Heroism', level: 2, description: '' },
    { name: 'Resist cold', level: 2, description: '' },
    { name: 'Resist fire', level: 2, description: '' },
    { name: 'Silence (15\' radius)', level: 2, description: '' },

    { name: 'Cure disease', level: 3, description: '' },
    { name: 'Dispel magic', level: 3, description: '' },
    { name: 'Magic vestments', level: 3, description: '' },
    { name: 'Remove curse', level: 3, description: '' },
    { name: 'Sacrifice', level: 3, description: '' },
    { name: 'Water walk', level: 3, description: '' },

    { name: 'Cure serious wounds', level: 4, description: '' },
    { name: 'Detect lie', level: 4, description: '' },
    { name: 'Divinaton', level: 4, description: '' },
    { name: 'Neutralize Poison', level: 4, description: '' },
    { name: 'Protection from evil (10\' radius)', level: 4, description: '' },
    { name: 'Spell immunity', level: 4, description: '' },

    { name: 'Commune', level: 5, description: '' },
    { name: 'Cure critical wounds', level: 5, description: '' },
    { name: 'Dispel evil', level: 5, description: '' },
    { name: 'Insect plague', level: 5, description: '' },
    { name: 'Quest', level: 5, description: '' },
    { name: 'True seeing', level: 5, description: '' },

    { name: 'Anti-magic shell', level: 6, description: '' },
    { name: 'Find the path', level: 6, description: '' },
    { name: 'Forbiddance', level: 6, description: '' },
    { name: 'Heal', level: 6, description: '' },
    { name: 'Tongues', level: 6, description: '' },
    { name: 'Word of recall', level: 6, description: '' },

    { name: 'Control the weather', level: 7, description: '' },
    { name: 'Earthquake', level: 7, description: '' },
    { name: 'Holy word', level: 7, description: '' },
    { name: 'Part water', level: 7, description: '' }
];

export const magicUserSpells: LotfpSpell[] = [

    // Level 1
    { name: 'Bookspeak', level: 1, description: '' },
    { name: 'Charm Person', level: 1, description: '' },
    { name: 'Comprehend Languages', level: 1, description: '' },
    { name: 'Detect Magic', level: 1, description: '' },
    { name: 'Enlarge', level: 1, description: '' },
    { name: 'Faerie Fire', level: 1, description: '' },
    { name: 'Feather Fall', level: 1, description: '' },
    { name: 'Floating Disc', level: 1, description: '' },
    { name: 'Hold Portal', level: 1, description: '' },
    { name: 'Identify', level: 1, description: '' },
    { name: 'Light', level: 1, description: '' },
    { name: 'Magic Aura', level: 1, description: '' },
    { name: 'Magic Missile', level: 1, description: '' },
    { name: 'Mending', level: 1, description: '' },
    { name: 'Message', level: 1, description: '' },
    { name: 'Shield', level: 1, description: '' },
    { name: 'Sleep', level: 1, description: '' },
    { name: 'Spider Climb', level: 1, description: '' },
    { name: 'Summon', level: 1, description: '' },
    { name: 'Unseen Servant', level: 1, description: '' },

    // Level 2
    { name: 'Audible Glamour', level: 2, description: '' },
    { name: 'Change Self', level: 2, description: '' },
    { name: 'Detect Invisible', level: 2, description: '' },
    { name: 'ESP', level: 2, description: '' },
    { name: 'Force of Forbidment', level: 2, description: '' },
    { name: 'Forget', level: 2, description: '' },
    { name: 'Invisibility', level: 2, description: '' },
    { name: 'Knock', level: 2, description: '' },
    { name: 'Levitate', level: 2, description: '' },
    { name: 'Light, Continual', level: 2, description: '' },
    { name: 'Locate Object', level: 2, description: '' },
    { name: 'Magic Mouth', level: 2, description: '' },
    { name: 'Mirror Image', level: 2, description: '' },
    { name: 'Phantasmal Force', level: 2, description: '' },
    { name: 'Ray of Enfeeblement', level: 2, description: '' },
    { name: 'Speak with Animals', level: 2, description: '' },
    { name: 'Stinking Cloud', level: 2, description: '' },
    { name: 'Wall of Fog', level: 2, description: '' },
    { name: 'Web', level: 2, description: '' },
    { name: 'Wizard Lock', level: 2, description: '' },

    // Level 3
    { name: 'Army of One', level: 3, description: '' },
    { name: 'Clairvoyance', level: 3, description: '' },
    { name: 'Detect Illusion', level: 3, description: '' },
    { name: 'Dispel Magic', level: 3, description: '' },
    { name: 'Explosive Runes', level: 3, description: '' },
    { name: 'False Alignment', level: 3, description: '' },
    { name: 'Fly', level: 3, description: '' },
    { name: 'Gaseous Form', level: 3, description: '' },
    { name: 'Gust of Wind', level: 3, description: '' },
    { name: 'Haste', level: 3, description: '' },
    { name: 'Hold Person', level: 3, description: '' },
    { name: 'Howl of the Moon', level: 3, description: '' },
    { name: 'Invisibility 10\' Radius', level: 3, description: '' },
    { name: 'Phantasmal Psychedelia', level: 3, description: '' },
    { name: 'Protection from Normal Missiles', level: 3, description: '' },
    { name: 'Secret Page', level: 3, description: '' },
    { name: 'Speak with Dead', level: 3, description: '' },
    { name: 'Strange Waters II', level: 3, description: '' },
    { name: 'Suggestion', level: 3, description: '' },
    { name: 'Water Breathing', level: 3, description: '' },

    // Level 4
    { name: 'Charm Monster', level: 4, description: '' },
    { name: 'Confusion', level: 4, description: '' },
    { name: 'Creation, Minor', level: 4, description: '' },
    { name: 'Dig', level: 4, description: '' },
    { name: 'Dimension Door', level: 4, description: '' },
    { name: 'Extension', level: 4, description: '' },
    { name: 'Globe of Invulnerability, Minor', level: 4, description: '' },
    { name: 'Hallucinatory Terrain', level: 4, description: '' },
    { name: 'Invisibility, Improved', level: 4, description: '' },
    { name: 'Mnemonic Enhancer', level: 4, description: '' },
    { name: 'Plant Growth', level: 4, description: '' },
    { name: 'Polymorph Others', level: 4, description: '' },
    { name: 'Polymorph Self', level: 4, description: '' },
    { name: 'Protection from Normal Weapons', level: 4, description: '' },
    { name: 'Seven Gates', level: 4, description: '' },
    { name: 'Shadow Monsters', level: 4, description: '' },
    { name: 'Speak with Plants', level: 4, description: '' },
    { name: 'Wall of Fire', level: 4, description: '' },
    { name: 'Wall of Ice', level: 4, description: '' },
    { name: 'Wizard Eye', level: 4, description: '' },

    // Level 5
    { name: 'Airy Water', level: 5, description: '' },
    { name: 'Animate Dead', level: 5, description: '' },
    { name: 'Chaos', level: 5, description: '' },
    { name: 'Cloudkill', level: 5, description: '' },
    { name: 'Contact Outer Sphere', level: 5, description: '' },
    { name: 'Creation, Major', level: 5, description: '' },
    { name: 'Faithful Hound', level: 5, description: '' },
    { name: 'Feeblemind', level: 5, description: '' },
    { name: 'Hold Monster', level: 5, description: '' },
    { name: 'Interposing Hand', level: 5, description: '' },
    { name: 'Magic Jar', level: 5, description: '' },
    { name: 'Passwall', level: 5, description: '' },
    { name: 'Secret Chest', level: 5, description: '' },
    { name: 'Stone Shape', level: 5, description: '' },
    { name: 'Telekinesis', level: 5, description: '' },
    { name: 'Teleport', level: 5, description: '' },
    { name: 'Transmute Rock to Mud', level: 5, description: '' },
    { name: 'Wall of Force', level: 5, description: '' },
    { name: 'Wall of Iron', level: 5, description: '' },
    { name: 'Wall of Stone', level: 5, description: '' },

    // Level 6
    { name: 'Animate Dead Monsters', level: 6, description: '' },
    { name: 'Barrier', level: 6, description: '' },
    { name: 'Contingency', level: 6, description: '' },
    { name: 'Death Spell', level: 6, description: '' },
    { name: 'Disintegrate', level: 6, description: '' },
    { name: 'Geas', level: 6, description: '' },
    { name: 'Glass Eye', level: 6, description: '' },
    { name: 'Globe of Invulnerability, Major', level: 6, description: '' },
    { name: 'Legend Lore', level: 6, description: '' },
    { name: 'Lucubration', level: 6, description: '' },
    { name: 'Mind Switch', level: 6, description: '' },
    { name: 'Move Earth', level: 6, description: '' },
    { name: 'Phantasmal Supergoria', level: 6, description: '' },
    { name: 'Projected Image', level: 6, description: '' },
    { name: 'Shades', level: 6, description: '' },
    { name: 'Speak with Monsters', level: 6, description: '' },
    { name: 'Stone to Flesh', level: 6, description: '' },
    { name: 'Suggestion, Mass', level: 6, description: '' },
    { name: 'Veil', level: 6, description: '' },
    { name: 'Weird Vortex', level: 6, description: '' },

    // Level 7
    { name: 'Animated Artwork', level: 7, description: '' },
    { name: 'Bestow Spell Ability', level: 7, description: '' },
    { name: 'Duo - Dimension', level: 7, description: '' },
    { name: 'Grasping Hand', level: 7, description: '' },
    { name: 'Instant Summons', level: 7, description: '' },
    { name: 'Invisibility, Mass', level: 7, description: '' },
    { name: 'Magic Sword', level: 7, description: '' },
    { name: 'Phase Door', level: 7, description: '' },
    { name: 'Power Word Stun', level: 7, description: '' },
    { name: 'Prismatic Sphere', level: 7, description: '' },
    { name: 'Prismatic Spray', level: 7, description: '' },
    { name: 'Prismatic Wall', level: 7, description: '' },
    { name: 'Remote Surveillance', level: 7, description: '' },
    { name: 'Reverse Gravity', level: 7, description: '' },
    { name: 'Simulacrum', level: 7, description: '' },
    { name: 'Spell Turning', level: 7, description: '' },
    { name: 'Statue', level: 7, description: '' },
    { name: 'Vanish', level: 7, description: '' },
    { name: 'Vision', level: 7, description: '' },
    { name: 'Witchlamp Aura', level: 7, description: '' },

    // Level 8
    { name: 'Antipathy / Sympathy', level: 8, description: '' },
    { name: 'Charm Person, Mass', level: 8, description: '' },
    { name: 'Clone', level: 8, description: '' },
    { name: 'Demand', level: 8, description: '' },
    { name: 'Maze', level: 8, description: '' },
    { name: 'Mind Blank', level: 8, description: '' },
    { name: 'Permanency', level: 8, description: '' },
    { name: 'Polymorph Any Object', level: 8, description: '' },
    { name: 'Symbol', level: 8, description: '' },
    { name: 'Trap the Soul', level: 8, description: '' },

    // Level 9
    { name: 'Imprisonment', level: 9, description: '' },
    { name: 'Lost Dweomer', level: 9, description: '' },
    { name: 'Power Word Kill', level: 9, description: '' },
    { name: 'Shape Change', level: 9, description: '' },
    { name: 'Temporal Stasis', level: 9, description: '' },
    { name: 'Time Stop', level: 9, description: '' }
];





